# Generated by Django 5.1.2 on 2025-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedcontent",
            name="is_displayed",
            field=models.BooleanField(default=True),
        ),
    ]
