# Generated by Django 5.1.2 on 2025-03-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0002_fixedcontent_is_displayed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FixedContent",
        ),
    ]
