# Generated by Django 5.1.2 on 2025-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fixed_contents", "0003_delete_fixedcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                ("name", models.CharField(max_length=64)),
                ("position", models.CharField(max_length=32)),
                (
                    "image",
                    models.ImageField(
                        default="org_members/default.png", upload_to="org_members"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
            },
        ),
    ]
