# Generated by Django 5.1.2 on 2025-03-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                ("name", models.CharField(max_length=64)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Upcoming Event",
                "verbose_name_plural": "Upcoming Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="organizationmembers",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
            },
        ),
    ]
