# Generated by Django 5.1.2 on 2025-03-12 07:27

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0005_upcomingevents_alter_organizationmembers_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaDisplays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        upload_to="media_displays",
                        validators=[utils.validators.validate_file_name_length],
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Display",
                "verbose_name_plural": "Media Displays",
            },
        ),
    ]
