# Generated by Django 5.1.2 on 2025-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0006_mediadisplays"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediadisplays",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Media Display",
                "verbose_name_plural": "Media Displays",
            },
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
