# Generated by Django 5.1.2 on 2025-03-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_contents", "0007_alter_mediadisplays_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediadisplays",
            name="priority",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
