# Generated by Django 5.1.2 on 2025-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
