# Generated by Django 5.1.2 on 2025-03-28 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notifications_target_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approve_announcement", "Approve Announcement"),
                    ("announcement_approved", "Announcement Approved"),
                    ("text_announcement_deactivated", "Text Announcement Deactivated"),
                    (
                        "video_announcement_deactivated",
                        "Video Announcement Deactivated",
                    ),
                    ("image_announcement_deactivated", "Text Announcement Deactivated"),
                    ("announcement_sequence_update", "Announcement Sequence Update"),
                    ("welcome_new_user", "Welcome new user"),
                    ("profile_update", "Profile Update"),
                    ("settings_update", "settings Update"),
                    ("organization_member_added", "Organization member added"),
                    ("organization_member_deleted", "Organization member deleted"),
                    ("organization_sequence_update", "Organization sequence update"),
                    ("upcoming_event_added", "Upcoming event added"),
                    ("upcoming_event_deleted", "Upcoming event deleted"),
                    ("media_display_added", "Media display added"),
                    ("media_sequence_update", "Media sequence update"),
                    ("media_display_deleted", "Media display deleted"),
                    ("calendar_event_added", "Calendar Event Added"),
                    ("calendar_event_deleted", "Calendar Event Deleted"),
                    ("calendar_event_updated", "Calendar Event Updated"),
                    ("calendar_settings_updated", "Calendar Settings Updated"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="target_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the object in its relative table",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target User/Recipient",
            ),
        ),
    ]
