# Generated by Django 5.1.2 on 2024-10-15 13:51

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[users.validators.id_number_validator],
                        verbose_name="ID Number",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("faculty", "Faculty")],
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("department_head", "Department Head"),
                            ("organizational_adviser", "Organizational Adviser"),
                            ("faculty_staff", "Faculty Staff"),
                            ("professor", "Professor"),
                        ],
                        max_length=32,
                        verbose_name="Position",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="Birthdate")),
                (
                    "image",
                    models.ImageField(
                        default="profile_pics/profile.png", upload_to="profile_pics"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
