# Generated by Django 5.1.2 on 2024-10-16 02:24

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(
                validators=[users.validators.birthdate_validator],
                verbose_name="Birthdate",
            ),
        ),
    ]
