# Generated by Django 5.1.2 on 2025-02-28 03:15

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_is_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewUserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "code",
                    models.CharField(
                        default=users.models.generate_unique_code, max_length=6
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("faculty", "Faculty")],
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("department_head", "Department Head"),
                            ("organizational_adviser", "Organizational Adviser"),
                            ("faculty_staff", "Faculty Staff"),
                            ("professor", "Professor"),
                        ],
                        max_length=32,
                        verbose_name="Position",
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                (
                    "expiration_date",
                    models.DateTimeField(default=users.models.date_after_7days),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "New User Invitation",
                "verbose_name_plural": "New User Invitations",
            },
        ),
    ]
