# Generated by Django 5.1.2 on 2025-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_newuserinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuserinvitation",
            name="is_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
