# Generated by Django 5.1.2 on 2025-03-05 06:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_newuserinvitation_is_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserinvitation",
            name="code",
            field=models.CharField(
                default=users.models.generate_unique_code, max_length=6, unique=True
            ),
        ),
    ]
