# Generated by Django 5.1.2 on 2025-03-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_newuserinvitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserinvitation",
            name="position",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("public_information_officer", "Public Information Officer"),
                    ("department_head", "Department Head"),
                    ("organizational_adviser", "Organizational Adviser"),
                    ("faculty_staff", "Faculty Staff"),
                    ("professor", "Professor"),
                ],
                max_length=32,
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("public_information_officer", "Public Information Officer"),
                    ("department_head", "Department Head"),
                    ("organizational_adviser", "Organizational Adviser"),
                    ("faculty_staff", "Faculty Staff"),
                    ("professor", "Professor"),
                ],
                max_length=32,
                verbose_name="Position",
            ),
        ),
    ]
