# Generated by Django 5.1.2 on 2024-11-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcements",
        ),
    ]
