# Generated by Django 5.1.2 on 2024-11-18 04:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Select the date and time when the announcement will be displayed. Default value of now.",
                verbose_name="Display start",
            ),
        ),
        migrations.CreateModel(
            name="TextAnnouncements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                ("details", models.JSONField()),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=40),
                        help_text="Duration for which the text announcement will be displayed",
                        verbose_name="Display duration",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_announcement",
                        to="announcements.announcements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Announcement",
                "verbose_name_plural": "Text Announcement",
            },
        ),
    ]
