# Generated by Django 5.1.2 on 2024-11-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_alter_announcements_start_date_textannouncements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textannouncements",
            name="announcement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_announcement",
                to="announcements.announcements",
            ),
        ),
    ]
