# Generated by Django 5.1.2 on 2024-11-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0005_alter_textannouncements_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
