# Generated by Django 5.1.2 on 2024-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0008_alter_textannouncements_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="start_date",
            field=models.DateTimeField(
                help_text="Select the date and time when the announcement will be displayed. Default value of now.",
                verbose_name="Display start",
            ),
        ),
    ]
