# Generated by Django 5.1.2 on 2024-11-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0009_alter_announcements_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="start_date",
            field=models.DateTimeField(
                help_text="Select the date and time when the announcement will be displayed",
                verbose_name="Display start",
            ),
        ),
    ]
