# Generated by Django 5.1.2 on 2025-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0012_alter_announcements_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
