# Generated by Django 5.1.2 on 2025-05-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0014_announcements_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcements",
            name="deleted_at",
        ),
    ]
