# Generated by Django 5.1.2 on 2025-05-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0015_remove_announcements_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
