# Generated by Django 5.1.2 on 2025-05-15 10:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0016_announcements_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgentAnnouncements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                ("title", models.JSONField()),
                ("description", models.JSONField()),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=40),
                        help_text="Duration for which the urgent announcement will be displayed.",
                        verbose_name="Display duration",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Urgent Announcement",
                "verbose_name_plural": "Urgent Announcements",
            },
        ),
    ]
