# Generated by Django 5.1.2 on 2025-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0017_urgentannouncements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UrgentAnnouncements",
        ),
    ]
