# Generated by Django 5.1.2 on 2025-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0019_urgentannouncements"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentannouncements",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
