# Generated by Django 5.1.2 on 2025-02-12 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
