# Generated by Django 5.1.2 on 2025-03-18 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0002_settings_show_calendar_settings_show_media_displays_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="media_displays_slide_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=5)),
        ),
        migrations.AddField(
            model_name="settings",
            name="organization_slide_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=5)),
        ),
        migrations.AddField(
            model_name="settings",
            name="upcoming_events_slide_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=5)),
        ),
    ]
