# Generated by Django 5.1.2 on 2025-03-21 11:25

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_settings_media_displays_slide_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="kiosk_calendar_grid_type",
            field=models.CharField(
                choices=[
                    ("dayGridMonth", "Monthly"),
                    ("timeGridWeek", "Weekly"),
                    ("timeGridDay", "Daily"),
                ],
                default="dayGridMonth",
                max_length=32,
                verbose_name="Kiosk Calendar Grid Type",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="kiosk_max_events",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Max number of events to display before it collapses in Kiosk Calendar",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="kiosk_show_events",
            field=models.BooleanField(
                default=True, verbose_name="Show events in Kiosk Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="kiosk_show_grid_controls",
            field=models.BooleanField(
                default=True, verbose_name="Show grid controls in Kiosk Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="kiosk_show_nav_controls",
            field=models.BooleanField(
                default=True, verbose_name="Show navigation controls in Kiosk Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="kiosk_show_weekends",
            field=models.BooleanField(
                default=True, verbose_name="Show weekends in Kiosk Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_calendar_grid_type",
            field=models.CharField(
                choices=[
                    ("dayGridMonth", "Monthly"),
                    ("timeGridWeek", "Weekly"),
                    ("timeGridDay", "Daily"),
                ],
                default="dayGridMonth",
                max_length=32,
                verbose_name="Web Calendar Grid Type",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_max_events",
            field=models.SmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Max number of events to display before it collapses in Web Calendar",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_show_events",
            field=models.BooleanField(
                default=True, verbose_name="Show events in Web Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_show_grid_controls",
            field=models.BooleanField(
                default=True, verbose_name="Show grid controls in Web Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_show_nav_controls",
            field=models.BooleanField(
                default=True, verbose_name="Show navigation controls in Web Calendar"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="web_show_weekends",
            field=models.BooleanField(
                default=True, verbose_name="Show weekends in Web Calendar"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="announcement_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Reference point of announcement syncing",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="media_displays_slide_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=5),
                verbose_name="Duration of Media Displays per slide",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="organization_slide_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=5),
                verbose_name="Duration of Organization per slide",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="show_calendar",
            field=models.BooleanField(default=True, verbose_name="Show Calendar"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="show_media_displays",
            field=models.BooleanField(default=True, verbose_name="Show Media Displays"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="show_organization",
            field=models.BooleanField(default=True, verbose_name="Show Organization"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="show_upcoming_events",
            field=models.BooleanField(
                default=True, verbose_name="Show Upcoming Events"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="show_weather_forecast",
            field=models.BooleanField(
                default=True, verbose_name="Show Weather Forecasts"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="upcoming_events_slide_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=5),
                verbose_name="Duration of Upcoming Events per slide",
            ),
        ),
    ]
