# Generated by Django 5.1.2 on 2025-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("own_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="location",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Event location"
            ),
        ),
    ]
